FROM google/cloud-sdk:slim

# Instala Python, git y otras herramientas necesarias
RUN apt-get update && apt-get install -y python3 python3-pip git


# Establece el entrypoint para ejecutar los comandos
ENTRYPOINT ["bash"]